pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/shaik9798/terraform0730.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Day2-introduction') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Day2-introduction') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Day2-introduction') {
                    sh 'terraform ${approve} -auto-approve'
                }
            }
        }
    }
}
